---
- name: Validate Netplan configuration
  ansible.builtin.command:
    argv:
      - /usr/sbin/netplan
      - generate
  changed_when: false
  when: not ansible_check_mode

- name: Apply Fabric Netplan configuration
  ansible.builtin.command:
    argv:
      - /usr/sbin/netplan
      - apply
  changed_when: true
  when: not ansible_check_mode
